name: API/v1 - CI
on:
  push:
    branches:
      - master
    paths:
      - 'api/v1/**'
  pull_request:
    branches:
      - master
    paths:
      - 'api/v1/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Packages
        run: npm install
        working-directory: api/v1/

      ## Build CovQuestions Package
      - name: Install covquestions
        run: npm install
        working-directory: covquestions-js/
      - name: Build covquestions package
        run: npm run build
        working-directory: covquestions-js/
      - name: Link covquestions package to api/v1/
        run: npm link ../../covquestions-js
        working-directory: api/v1/

      - name: Test App
        run: npm run test
        working-directory: api/v1/
      - name: Build App
        run: npm run build-api
        working-directory: api/v1/
      - name: Build Swagger
        run: npm run build-swagger
        working-directory: api/v1/
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: API
          path: api/v1/dist

      - name: Deploy ðŸš€
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: api/v1/dist
          clean: true
          # Exclude files from covquestions-documentation
          clean-exclude: |
            /index.html
            modules.html
            classes/**
            assets/**
            interfaces/**
