name: NPM - Release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: "0"
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Packages
        run: lerna exec npm install

      ## Build Covquesitions Package
      - name: Build covquestions package
        run: npm run build
        working-directory: covquestions-js/

      ## Build covscript Package
      - name: Link covquestions package to covscript
        run: npm link ../covquestions-js
        working-directory: covscript/
      - name: Build covscript package
        run: npm run build
        working-directory: covscript/

      # Build covquestions editor
      - name: Link covscript package to React App
        run: npm link ../covscript
        working-directory: covquestions-editor-app/
      - name: Link covquestions package to React App
        run: npm link ../covquestions-js
        working-directory: covquestions-editor-app/

      - name: Build App
        run: npm run build
        working-directory: covquestions-editor-app/

      - name: Setup NPM Authentication
        run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup git user
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Release all packages
        run: npx lerna publish --yes --no-verify-access
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Update Documentation
      - name: Build App
        run: npm run doc
        working-directory: covquestions-js/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: API
          path: covquestions-js/docs

      - name: Deploy ðŸš€
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: covquestions-js/docs
          clean: true
          # Ignore API Files
          clean-exclude: |
            swagger/**
            questionnaires.json
            questionnaires/**
